// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZEaLzL_STmK3PcOzEZQe2A0NIDtvd9y4',
    appId: '1:856063124399:web:e3bc440ff02c312871c55a',
    messagingSenderId: '856063124399',
    projectId: 'smart-icu-system',
    authDomain: 'smart-icu-system.firebaseapp.com',
    databaseURL: 'https://smart-icu-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-icu-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxa0QNDjLScSGcfOAK5bfGh7CuKU8QZIs',
    appId: '1:856063124399:android:c3be49edaabb0b6f71c55a',
    messagingSenderId: '856063124399',
    projectId: 'smart-icu-system',
    databaseURL: 'https://smart-icu-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-icu-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8YBbUuHMdLA-SqNVtKb6yz-06DFR6718',
    appId: '1:856063124399:ios:55bb97cc9b6e65ae71c55a',
    messagingSenderId: '856063124399',
    projectId: 'smart-icu-system',
    databaseURL: 'https://smart-icu-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-icu-system.appspot.com',
    iosBundleId: 'com.example.icu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8YBbUuHMdLA-SqNVtKb6yz-06DFR6718',
    appId: '1:856063124399:ios:0871fb4d48cd97aa71c55a',
    messagingSenderId: '856063124399',
    projectId: 'smart-icu-system',
    databaseURL: 'https://smart-icu-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-icu-system.appspot.com',
    iosBundleId: 'com.example.icu.RunnerTests',
  );
}
